"""Pydantic models shared across the API. These mirror the frontend types."""
from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


def _uid(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


def _now() -> float:
    return time.time()


# --- The Mixer -------------------------------------------------------------

PillCategory = Literal[
    "mood", "genre", "instrument", "vocal", "feeling", "pacing", "era", "keyword"
]


class Pill(BaseModel):
    id: str
    category: PillCategory
    label: str
    # 0..1 intensity; how strongly this pill should weigh in the prompt.
    weight: float = 1.0


class SamplingParams(BaseModel):
    temperature: float = 1.0
    top_p: float = 0.95
    top_k: int = 100
    repetition_penalty: float = 1.2


class GenerationOptions(BaseModel):
    """All the user-tunable model options, mapped onto YuE2's SongRequest."""

    cot: Literal["full", "melody", "off"] = "full"
    seed: int = Field(default_factory=lambda: 831001)
    cfg_scale: Optional[float] = None
    max_duration: int = 120  # seconds
    sampling: SamplingParams = Field(default_factory=SamplingParams)


class GenerateRequest(BaseModel):
    """What the frontend POSTs to start a generation.

    Either provide an explicit `style` string, or `pills` (which the prompt
    composer turns into a style string). `lyrics` may be provided directly or
    generated by the lyrics assistant beforehand.
    """

    title: Optional[str] = None
    style: Optional[str] = None
    pills: list[Pill] = Field(default_factory=list)
    lyrics: str = ""
    abc: Optional[str] = None
    options: GenerationOptions = Field(default_factory=GenerationOptions)
    engine: Optional[str] = None  # override the default engine ("stub"|"yue2")


# --- Jobs ------------------------------------------------------------------


class JobStatus(str, Enum):
    queued = "queued"
    downloading = "downloading"
    planning = "planning"
    generating = "generating"
    synthesizing = "synthesizing"
    decoding = "decoding"
    done = "done"
    error = "error"
    cancelled = "cancelled"


class Job(BaseModel):
    id: str = Field(default_factory=lambda: _uid("job"))
    status: JobStatus = JobStatus.queued
    progress: float = 0.0  # 0..1
    stage: str = "queued"
    message: str = ""
    created_at: float = Field(default_factory=_now)
    updated_at: float = Field(default_factory=_now)
    title: str = "Untitled"
    style: str = ""
    engine: str = "stub"
    track_id: Optional[str] = None
    error: Optional[str] = None
    eta_seconds: Optional[float] = None


# --- Tracks & Playlists ----------------------------------------------------


class Track(BaseModel):
    id: str = Field(default_factory=lambda: _uid("trk"))
    title: str
    style: str = ""
    lyrics: str = ""
    pills: list[Pill] = Field(default_factory=list)  # the mix used, for Remix
    audio_url: str = ""  # served path, e.g. /media/audio/<file>.flac
    cover_url: Optional[str] = None
    duration: float = 0.0
    sample_rate: int = 48000
    seed: int = 0
    engine: str = "stub"
    created_at: float = Field(default_factory=_now)


class Playlist(BaseModel):
    id: str = Field(default_factory=lambda: _uid("pl"))
    name: str
    track_ids: list[str] = Field(default_factory=list)
    order: float = Field(default_factory=_now)  # sort key; lower = higher up
    created_at: float = Field(default_factory=_now)


class PlaylistCreate(BaseModel):
    name: str


class PlaylistUpdate(BaseModel):
    name: Optional[str] = None
    track_ids: Optional[list[str]] = None


class PlaylistReorder(BaseModel):
    order: list[str]  # playlist ids in the desired order


class TrackUpdate(BaseModel):
    title: Optional[str] = None


# --- Prompt composer / lyrics assistant ------------------------------------


class ComposeRequest(BaseModel):
    pills: list[Pill] = Field(default_factory=list)
    extra: str = ""  # free-text the user typed in the mixer
    ai: bool = False  # True = LLM-refine (button); False = instant deterministic


class ComposeResponse(BaseModel):
    style: str
    used_llm: bool = False


class LyricsRequest(BaseModel):
    theme: str = ""
    pills: list[Pill] = Field(default_factory=list)
    structure: list[str] = Field(default_factory=lambda: ["verse", "chorus", "verse", "chorus"])


class LyricsResponse(BaseModel):
    lyrics: str
    used_llm: bool = False


# --- Export ----------------------------------------------------------------


class ExportRequest(BaseModel):
    folder: str
    format: Literal["flac", "wav"] = "flac"
    filename: Optional[str] = None  # without extension; defaults to the title


class ExportResponse(BaseModel):
    path: str
    folder: str
    filename: str


class SaveRequest(BaseModel):
    path: str  # absolute destination file path (from the native Save dialog)
